name: Java CI with Maven 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Compile
      run: mvn clean install

    - name: Package
      run: mvn package
      
    - name: Unit Test
      run: mvn test
      
    - name: List current directory
      run: ls -la
      
    - name: target folder content
      run: |
        cd target
        ls -la
      
    - name: build & SonarQube analysis
      run: |
        mvn verify sonar:sonar -Dsonar.projectKey=testrepo1 -Dsonar.login=4c4e9b9c168315a700a1b32a90e04f61931a75ec -Dsonar.host.url=https://sonarcloud.io/
        sleep 60
        
    - name: Creating docker images for apache and tomcat
      run: |
        docker pull alpine
        docker pull httpd
        docker pull tomcat
        
        
